### ISSUE TITLE
task list 

### ISSUE THREAD

**Issue by meb326** [adeslatt/methylSeqCaptureSeq#5]
- [ ] for each command in bash script, make into a Nextflow process and test with test data (https://github.com/nf-core/test-datasets/tree/methylseq/testdata)

- [ ] piggy back from tools with code already written in Nextflow 

- [ ] create new code in nextflow for biscuit and wgbs_tools

- [ ] create a new docker file and build image for wgbs_tools 

- [ ] create Flowcraft components for each Nextflow process 

- [ ] build a pipeline with Flowcraft 

- [ ] run Nextflow pipeline on CloudOS (lifebit)
